[package]
name = "treeflection_derive_tests"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]

[dependencies]
treeflection = { path = "../treeflection" }
treeflection_derive = { path = "../treeflection_derive" }
