#[derive(Debug, PartialEq, Clone)]
pub enum NodeToken {
    ChainProperty (String),
    ChainIndex (usize),
    ChainKey (String),
    ChainContext,
    Help,
    Edit,
    GetKeys,
    Get,
    Set (String),
    SetDefault,
    SetVariant (String),
    CopyFrom,
    PasteTo,
    Insert,
    InsertIndex (usize),
    InsertKey (String),
    InsertIndexKey (usize, String),
    Remove,
    RemoveIndex (usize),
    RemoveKey (String),
    Custom (String),
}
