[package]
name = "treeflection_derive"
version = "0.1.16"
authors = ["Rukai <rubickent@gmail.com>"]
description = "#[derive(Node)] macro for the Treeflection library"
license = "MIT"
repository = "https://github.com/rukai/treeflection"
keywords = ["reflection", "tree", "treeflection"]

[lib]
proc-macro = true

[dependencies]
syn = "0.12"
quote = "0.4"
serde = "1.0"
serde_json = "1.0"
proc-macro2 = { version = "0.2" }

[dev-dependencies]
matches = "0.1"
treeflection = { path = "../treeflection" }
serde_derive = "1.0"
