[package]
name = "treeflection_derive"
version = "0.1.11"
authors = ["Rukai <rubickent@gmail.com>"]
description = "#[derive(Node)] macro for the Treeflection library"
license = "MIT"
repository = "https://github.com/rukai/treeflection"
keywords = ["reflection", "tree", "treeflection"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"
serde = "0.9"
serde_json = "0.9"
