[package]
name = "treeflection_derive"
version = "0.1.14"
authors = ["Rukai <rubickent@gmail.com>"]
description = "#[derive(Node)] macro for the Treeflection library"
license = "MIT"
repository = "https://github.com/rukai/treeflection"
keywords = ["reflection", "tree", "treeflection"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
matches = "0.1.4"
treeflection = { path = "../treeflection" }
treeflection_derive = { path = "../treeflection_derive" }
serde_derive = "1.0"
