[package]
name = "treeflection_derive"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.10"
quote = "0.3.5"

[dev-dependencies]
treeflection = { path = "../treeflection" }
