[package]
name = "treeflection_derive"
version = "0.1.1"
authors = ["Rukai <rubickent@gmail.com>"]
description = "#[derive(Node)] macro for the Treeflection library"
license = "MIT"
repository = "https://github.com/rukai/treeflection"
keywords = ["reflection", "tree", "treeflection"]

[lib]
proc-macro = true

[dependencies]
syn = "0.10"
quote = "0.3.5"
